site_name: wiki
site_description: Personal wiki, open to collaboration!
site_url: https://github.com/iancleary/wiki

theme:
    name: 'material'

repo_name: iancleary/wiki
repo_url: https://github.com/iancleary/wiki
edit_uri: ''

nav:
    - Introduction: 'index.md'
    - Local Computer Setup: 'local-computer.md'
    - Ansible Setup: 'ansible-hosts.md'
    - Raspberry Pi - UniFi Controller: 'rpi-unifi.md'
